package framework;

import java.util.Hashtable;

/**
 * XSA_Loader responsible to set XModule hashtable with the implimented functions.
 * This file is auto generated by the XModule "generate" step, and should not be edit
 * manually.
 */
public class XSA_Loader
{
    public static void UpdateLoader(Hashtable[] IN_hashes)
    {
        String function = "UpdateLoader";
        int level = XSA_Framework.XSA_DEBUG_DETAIL + 10;
        XSA_Framework.XSA_WriteDebugEnter(level, function);
        Hashtable XSA_GetEntityHash = IN_hashes[XSA_Framework.XSA_GET_ENTITY_HASH];

        XSA_GetEntityHash.put("ConnectorInit", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ConnectorTerm", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("SessionInit", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("SessionTerm", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("SystemPropertiesGet", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("SystemPropertiesSet", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("SystemActiveQuery", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("AccountGet", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("AccountAdd", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("AccountUpdate", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("AccountDelete", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("VerifyAdminPassword","Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("GroupGet", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("GroupAdd", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("GroupUpdate", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("GroupDelete", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ConnectionGet", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ConnectionAdd", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ConnectionUpdate", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ConnectionDelete", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ContainerGet", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ContainerAdd", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ContainerUpdate", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ContainerDelete", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ResourceGet", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ResourceAdd", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ResourceUpdate", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ResourceDelete", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("AceGet", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("AceAdd", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("AceUpdate", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("AceDelete", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("IsAccountInContainer", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("IsGroupInContainer", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("IsContainerInContainer", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ManageSystemInit", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("ManageSystemTerm", "Y"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("TransactionStart", "N"); // @@@EXIST_TAG@@@
        XSA_GetEntityHash.put("TransactionEnd", "N"); // @@@EXIST_TAG@@@

        XSA_Framework.XSA_WriteDebugExit(level, function, 0);
    }
}
