#!/bin/ksh
echo "*******************************************************************************"
echo "* This script will insert the new connector to the ESS server          	    *"
echo "*******************************************************************************"
echo "Please enter ess administrator name:"
read ESS_USR
echo "Please enter ess administrator password:"
stty -echo
read ESS_PWD
stty echo
COMMAND="REFRESH rss_type WITH rss_type= \"SINAV\" SET description= \"\" , predefined_type= \"0\" , active_type= \"1\" , max_pwd_len= \"128\" , pwd_reset_add_user= \"1\" , pwd_reset_chg_pwd= \"0\" , pwd_on_restore= \"0\" , requires_user_group= \"Not Supported\" , case_sensitivity= \"Ignore\" , permanent_ace= \"0\" , rss_upd_defgrp= \"Keep\" , del_ug_when= \"Not Connected to Users\" , get_conn_on_ug_add= \"0\" , get_conn_on_ug_upd= \"0\" , get_conn_on_usr_add= \"0\" , get_conn_on_usr_upd= \"0\" , get_conn_on_intrcpt_usr_upd= \"0\" , sync_user_on_conn_chg= \"0\" , get_acl_on_res_upd= \"0\" , relative_position_ace= \"0\" , rss_supports_advanced_load= \"1\" , user_define_res_type= \"0\" , rss_supports_oe= \"0\" , pw_sync_self_admin= \"0\" , names_case_sensitive= \"0\" , admin_password_required= \"1\" , user_name_type_check= \"%512s\" , user_grp_type_check= \"%512s\" , resource_type_check= \"%512s\" , resource_type_type_check= \"%512s\";SAVE_DEFINITION rules;"
echo $COMMAND > input.$$
ess batchrun -i input.$$  -U ${ESS_USR} -P ${ESS_PWD}
rm input.$$
COMMAND="REFRESH_ALL keyword WITH keyword_name= \"SINAV_XSA_ACE_RESNAME\" ,entity= \"ace\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"Ace Resource\" , data_type= \"char\" , tab= \"General\" , keyword_order= \"32\" , __99__NULL= \"N\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\",__99__ACCESS.LIMITED= \"1\",__99__MANDATORY= \"1\",__99__MANDATORY.INSERT= \"1\",__99__MANDATORY.UPDATE= \"1\",__99__MANDATORY.DELETE= \"1\", __99__READONLY_IN_UPDATE= \"1\" , __99__DIM= \"60x2\" , __99__LENGTH= \"100\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_XSA_ACE_RESTYPE\" ,entity= \"ace\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"Ace Resource Type\" , data_type= \"char\" , tab= \"General\" , keyword_order= \"33\" , __99__NULL= \"N\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\",__99__ACCESS.LIMITED= \"1\",__99__MANDATORY= \"1\",__99__MANDATORY.INSERT= \"1\",__99__MANDATORY.UPDATE= \"1\",__99__MANDATORY.DELETE= \"1\", __99__READONLY_IN_UPDATE= \"1\" , __99__LENGTH= \"20\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_NO_USUARIO\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"NO_USUARIO\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"34\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_UNIDADE\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_UNIDADE\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"35\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_SENHA\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_SENHA\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"36\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_SIS_DEFAUL\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_SIS_DEFAUL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"37\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_DT_ALT_SENHA\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"DT_ALT_SENHA\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"38\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_IMPR_REMOT\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_IMPR_REMOT\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"39\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_SIT_USU\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_SIT_USU\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"40\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_DT_ULT_ACESSO\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"DT_ULT_ACESSO\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"41\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_SUREG_LOT\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_SUREG_LOT\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"42\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_CEADM_AUT\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_CEADM_AUT\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"43\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_SUREG_AUT\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_SUREG_AUT\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"44\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_UNID_AUT\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_UNID_AUT\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"45\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_ID_DIRETORIA\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"ID_DIRETORIA\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"46\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_QT_ACESSOS\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"QT_ACESSOS\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"47\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_QT_MENS_GERAL\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"QT_MENS_GERAL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"48\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_TERMINAL\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_TERMINAL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"49\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_QT_MENS_PERFIL\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"QT_MENS_PERFIL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"50\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_ID_STATUS\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"ID_STATUS\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"51\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_ID_CEF\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"ID_CEF\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"52\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_DT_PRV_DESL\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"DT_PRV_DESL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"53\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_NO_REMOT\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_NO_REMOT\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"54\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_FUNCAO\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_FUNCAO\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"55\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CO_SEGMENTO\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CO_SEGMENTO\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"56\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_NU_CNPJ\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"NU_CNPJ\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"57\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_NU_MATR_EMP\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"NU_MATR_EMP\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"58\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_NU_CA_EN_FISICA\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"NU_CA_EN_FISICA\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"59\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_SISTEMA\" ,entity= \"user_group\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_SISTEMA\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"60\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_PERFIL\" ,entity= \"user_group\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"CD_PERFIL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"61\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_NO_PERFIL\" ,entity= \"user_group\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"User Defined\" , keyword_label= \"NO_PERFIL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"62\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
"
echo $COMMAND > input.$$
ess batchrun -i input.$$  -S~ -s, -U ${ESS_USR} -P ${ESS_PWD}
rm input.$$
sleep 2
COMMAND="DELETE_ALL keyword WITH keyword_rsstype = \"SINAV\";"
echo $COMMAND > input.$$
ess batchrun -i input.$$  -U ${ESS_USR} -P ${ESS_PWD}
rm input.$$
COMMAND="REFRESH_ALL keyword WITH keyword_name= \"SINAV_XSA_ACE_RESNAME\" ,entity= \"ace\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"Ace Resource\" , data_type= \"char\" , tab= \"General\" , keyword_order= \"32\" , __99__NULL= \"N\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\",__99__ACCESS.LIMITED= \"1\",__99__MANDATORY= \"1\",__99__MANDATORY.INSERT= \"1\",__99__MANDATORY.UPDATE= \"1\",__99__MANDATORY.DELETE= \"1\", __99__READONLY_IN_UPDATE= \"1\" , __99__DIM= \"60x2\" , __99__LENGTH= \"100\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_XSA_ACE_RESTYPE\" ,entity= \"ace\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"Ace Resource Type\" , data_type= \"char\" , tab= \"General\" , keyword_order= \"33\" , __99__NULL= \"N\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\",__99__ACCESS.LIMITED= \"1\",__99__MANDATORY= \"1\",__99__MANDATORY.INSERT= \"1\",__99__MANDATORY.UPDATE= \"1\",__99__MANDATORY.DELETE= \"1\", __99__READONLY_IN_UPDATE= \"1\" , __99__LENGTH= \"20\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_NO_USUARIO\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"NO_USUARIO\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"34\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_UNIDADE\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_UNIDADE\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"35\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_SENHA\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_SENHA\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"36\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_SIS_DEFAUL\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_SIS_DEFAUL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"37\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_DT_ALT_SENHA\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"DT_ALT_SENHA\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"38\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_IMPR_REMOT\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_IMPR_REMOT\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"39\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_SIT_USU\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_SIT_USU\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"40\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_DT_ULT_ACESSO\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"DT_ULT_ACESSO\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"41\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_SUREG_LOT\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_SUREG_LOT\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"42\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_CEADM_AUT\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_CEADM_AUT\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"43\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_SUREG_AUT\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_SUREG_AUT\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"44\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_UNID_AUT\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_UNID_AUT\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"45\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_ID_DIRETORIA\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"ID_DIRETORIA\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"46\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_QT_ACESSOS\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"QT_ACESSOS\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"47\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_QT_MENS_GERAL\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"QT_MENS_GERAL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"48\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_TERMINAL\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_TERMINAL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"49\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_QT_MENS_PERFIL\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"QT_MENS_PERFIL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"50\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_ID_STATUS\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"ID_STATUS\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"51\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_ID_CEF\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"ID_CEF\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"52\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_DT_PRV_DESL\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"DT_PRV_DESL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"53\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_NO_REMOT\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_NO_REMOT\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"54\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_FUNCAO\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_FUNCAO\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"55\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CO_SEGMENTO\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CO_SEGMENTO\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"56\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_NU_CNPJ\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"NU_CNPJ\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"57\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_NU_MATR_EMP\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"NU_MATR_EMP\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"58\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_NU_CA_EN_FISICA\" ,entity= \"rss_user\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"NU_CA_EN_FISICA\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"59\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_SISTEMA\" ,entity= \"user_group\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_SISTEMA\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"60\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_CD_PERFIL\" ,entity= \"user_group\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"CD_PERFIL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"61\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
REFRESH_ALL keyword WITH keyword_name= \"SINAV_NO_PERFIL\" ,entity= \"user_group\" , keyword_rsstype= \"SINAV\" , SET entry_type= \"Predefined\" , keyword_label= \"NO_PERFIL\" , data_type= \"text\" , tab= \"SINAV Parameters\" , keyword_order= \"62\" , __99__NULL= \"Y\" , __99__ENCRYPT= \"0\" , __99__DB_DFL= \"\" , __99__DIM= \"60x2\" , __99__LENGTH= \"255\";
"
echo $COMMAND > input.$$
ess batchrun -i input.$$  -S~ -s, -U ${ESS_USR} -P ${ESS_PWD}
rm input.$$


